[package]
name = "minidemo"
version = "0.1.0"
authors = ["Filip Szczepański <jazz2rulez@gmail.com>"]

[build-dependencies]
image = "0.19.0"

[dependencies]
minifb = "0.10.4"
game_time = "0.2.0"

[profile.dev]
opt-level = 1
debug-assertions = false

[profile.release]
opt-level = 3
lto = true
panic = 'abort'